### ISSUE TITLE
Piwigo with an Apache reverse proxy -> links broken

### ISSUE THREAD

**Issue by cybermcm** [linuxserver/docker-piwigo#16]
I'm trying to use this docker image with an Apache reverse proxy and a subpath, e.g. https://xyz.net/piwigo.
It works but not all of it. A lot of icons are broken and some links too. E.g. when I log in I'm getting redirected to the wrong url. Start page -> log in -> redirection to https://xyz.net instead of https://xyz.net/piwigo

docker compose file:
```
piwigo:
  depends_on:
   - sql
  image: linuxserver/piwigo:latest
  container_name: piwigo
  restart: always
  ports:
   - "127.0.0.1:20008:80"
  volumes:
   - /etc/timezone:/etc/timezone:ro
   - /etc/localtime:/etc/localtime:ro
   - /opt/piwigo:/config
  networks:
   - sql
```

relevant apache config:
```
RewriteRule ^/piwigo$ /piwigo/ [R,L]
ProxyPass "/piwigo" "http://localhost:20008"
ProxyPassReverse "/piwigo" "http://localhost:20008"
```
Any ideas how to get this config working?
